### ISSUE TITLE
Can you please add an executable to the new release?

### ISSUE THREAD

**Issue by aufbakanleitung** [nordcloud/assume-role-arn#40]
https://github.com/nordcloud/assume-role-arn/releases/tag/v0.3.6 doesn't contain an assume-role-arn-linux and assume-role-arn-osx yet.

**Comment by mescam** [comment]
Hello,

thank you for submitting this issue, I wonder what happened with our pipeline for this. I will try to fix this now.

**Comment by mescam** [comment]
It looks like travis changed something and the builds are failing to deploy and my config looks outdated. I hate when it happens. I will need to learn how to do this properly or migrate to something I know better.
Again, I am very sorry for the inconvenience, the fix should be ready in 1-2 days.

**Comment by mescam** [comment]
Hi @aufbakanleitung 

I was able to fix our release pipeline. In the meantime I've merged some dependency updates, so you can start using just released version https://github.com/nordcloud/assume-role-arn/releases/tag/v0.3.8
All the artifacts should be working properly

Please reopen this issue in case of any problems,

BR,
Jakub

**Comment by aufbakanleitung** [comment]
Fantastic, thank you!
