### ISSUE TITLE
assume-role-arn -version prints v0.3.4

### ISSUE THREAD

**Issue by BartoszZawadzki** [nordcloud/assume-role-arn#44]
I've downloaded assume-role-arn v0.3.8 and when executing:
`bash-5.0# assume-role-arn -version
assume-role-arn v0.3.4 (23d9db18bb7982c33708c8cd59c72d97b284fe4c)`

This is the case for both osx and linux versions.

It seems that the version is not bumped after release 0.3.4:
https://github.com/nordcloud/assume-role-arn/blob/master/cmd/assume-role-arn/version.go

**Comment by mescam** [comment]
Hi,

thank you for submitting this issue, I will try to fix this during next few days.

Best regards,
Jakub

**Comment by mescam** [comment]
Hi,

sorry for this delayed response, I just published version v0.3.9 with fixed... versions ;)
Now it is injected during compilation, so the issue won't happen again.

Best regards,
Jakub
