### ISSUE TITLE
ignoreCache should ignore caching entirely

### ISSUE THREAD

**Issue by tdi** [nordcloud/assume-role-arn#8]
Even if you set ignoreCache, assume-role-arn is trying to cache the credentials. this should not happen. Now when you run the tool in e.g. alpine docker image you keep seeing these:

`time="2019-12-01T22:58:57Z" level=error msg="failed to cache credentials" error="open /root/.cache/assume-role-be62a54dd201c68e3a76a37b682f78dd21bf46b31f781423d80606e252c53b96: no such file or directory"`

Even though the `-ignoreCache` flag was passed.

**Comment by tdi** [comment]
Maybe something like this could be implemented ? I mean ofc the interfaces not using go-cache. 

https://carlosbecker.com/posts/golang-cache-interface/

**Comment by kwilczynski** [comment]
Hi @tdi, thank you for bringing this to our attention!

To my understanding, the linked article talks more about approach to memoization. It's a good pattern, but in our case we have simple on-disk file-based cache. We simply need to ensure that when we are about to create the cache file, we also create the cache directory returned by `os.UserCacheDir()` and set the permission to `0755`.

The following function has to change:

https://github.com/nordcloud/assume-role-arn/blob/8ce9f507538df074660b7a8c8bf983a8b0c7d888/cmd/assume-role-arn/creds_cache.go#L61-L84

**Comment by tdi** [comment]
Yeah I just linked the article as an example of how to organize interfaces.
